name: abridge
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - asgiref=3.4.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=36.0.2
  - cycler=0.11.0
  - daal4py=2021.5.0
  - dal=2021.5.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - django=3.2.5
  - djangorestframework=3.13.1
  - entrypoints=0.3
  - executing=0.8.3
  - flake8=4.0.1
  - fonttools=4.32.0
  - freetype=2.11.0
  - future=0.18.2
  - giflib=5.2.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.2.0
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mccabe=0.7.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpi=1.0
  - mpich=3.3.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nltk=3.7
  - numexpr=2.8.1
  - numpy-base=1.21.5
  - oauthlib=3.2.0
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - psycopg2=2.8.6
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pyflakes=2.4.0
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.2
  - python-twitter=3.5
  - python_abi=3.8
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1.2
  - regex=2022.3.15
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2021.5.0
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=61.2.0
  - sqlite=3.38.2
  - sqlparse=0.4.1
  - stack_data=0.2.0
  - tbb=2021.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - typing_extensions=4.1.1
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - absl-py==1.0.0
      - anyascii==0.3.1
      - astunparse==1.6.3
      - cachetools==5.0.0
      - contractions==0.1.68
      - dill==0.3.4
      - flatbuffers==2.0
      - gast==0.5.3
      - google-auth==2.6.5
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.44.0
      - h5py==3.6.0
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - libclang==13.0.0
      - markdown==3.3.6
      - numpy==1.22.3
      - opt-einsum==3.3.0
      - protobuf==3.20.0
        - pyahocorasick==1.4.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
        - pyfunctional==1.4.3
      - rsa==4.8
      - six==1.15.0
        - tabulate==0.8.9
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
        - tensorflow-addons==0.16.1
      - tensorflow-macos==2.8.0
      - tensorflow-metal==0.4.0
      - termcolor==1.1.0
        - textsearch==0.0.21
      - tf-estimator-nightly==2.8.0.dev2021122109
        - typeguard==2.13.3
      - werkzeug==2.1.1
      - wrapt==1.14.0
      - zipp==3.8.0
