name: abridge
channels:
  - apple
  - anaconda
  - conda-forge
dependencies:
  - anyio=3.5.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asgiref=3.5.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.11.1
  - bleach=5.0.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.14.6
  - charset-normalizer=2.0.12
  - click=8.1.2
  - colorama=0.4.4
  - cryptography=36.0.2
  - cycler=0.11.0
  - cython=0.29.28
  - dataclasses=0.8
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - django=4.0
  - djangorestframework=3.13.1
  - entrypoints=0.4
  - executing=0.8.3
  - filelock=3.6.0
  - flit-core=3.7.1
  - fonttools=4.32.0
  - freetype=2.10.4
  - future=0.18.2
  - gensim=4.1.2
  - giflib=5.2.1
  - grpcio=1.45.0
  - h5py=3.6.0
  - hdf5=1.12.1
  - huggingface_hub=0.5.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.7.0
  - ipykernel=6.13.0
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.1
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyter_server=1.16.0
  - jupyterlab=3.3.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=1.1.0
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libcxx=13.0.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0.dev0
  - libgfortran5=11.0.1.dev0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.3.7
  - nbclient=0.5.13
  - nbconvert=6.4.5
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - ninja=1.10.2
  - nltk=3.6.7
  - notebook=6.4.10
  - notebook-shim=0.1.0
  - numpy=1.21.6
  - oauthlib=3.2.0
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.0.4
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - prompt_toolkit=3.0.29
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.8
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python-twitter=3.5
  - python_abi=3.8
  - pytorch=1.11.0
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - readline=8.1
  - regex=2022.3.15
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - sacremoses=0.0.53
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - sentencepiece=0.1.96
  - setuptools=62.1.0
  - sleef=3.5.1
  - smart_open=5.2.1
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.38.2
  - sqlparse=0.4.2
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tensorflow-deps=2.8.0
  - terminado=0.13.3
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tokenizers=0.10.3
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - transformers=4.16.2
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - absl-py==1.0.0
    - anyascii==0.3.1
    - astunparse==1.6.3
    - cachetools==5.0.0
    - certifi==2021.10.8
    - contractions==0.1.68
    - dill==0.3.4
    - flatbuffers==2.0
    - gast==0.5.3
    - google-auth==2.6.5
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - libclang==13.0.0
    - markdown==3.3.6
    - opt-einsum==3.3.0
    - protobuf==3.20.0
    - pyahocorasick==1.4.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyfunctional==1.4.3
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - rsa==4.8
    - six==1.15.0
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-addons==0.16.1
    - tensorflow-macos==2.8.0
    - tensorflow-metal==0.4.0
    - termcolor==1.1.0
    - textsearch==0.0.21
    - tf-estimator-nightly==2.8.0.dev2021122109
    - typeguard==2.13.3
    - werkzeug==2.1.1
    - wordcloud==1.8.1
    - wrapt==1.14.0
